name = "festival-atlas-worker"
main = "index.js"
compatibility_date = "2024-09-23"

[[d1_databases]]
binding = "DB"
database_name = "festival-atlas-vault"
database_id = "8cebdbf8-c3f7-40e4-9d1a-e7174909601e"
